name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  #  CLAVE para Workload Identity

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #  Autenticación SIN JSON (Workload Identity)
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/328737502436/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@analitica-contact-center-dev.iam.gserviceaccount.com

      #  Configurar gcloud
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure project
        run: gcloud config set project analitica-contact-center-dev

      #  Build imagen
      - name: Build Docker image
        run: |
          gcloud builds submit . \
          --tag gcr.io/analitica-contact-center-dev/cuentasmedicas-siifa \
          --async
      
      #  Deploy a Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cuentasmedicas-siifa \
          --image gcr.io/analitica-contact-center-dev/cuentasmedicas-siifa \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars SIIFA_USER=${{ secrets.SIIFA_USER }},SIIFA_PASSWORD="${{ secrets.SIIFA_PASSWORD }}",SIIFA_BASE_AUTH=${{ secrets.SIIFA_BASE_AUTH }},SIIFA_BASE_API=${{ secrets.SIIFA_BASE_API }},PROJECT_ID=${{ secrets.PROJECT_ID }},DATASET=${{ secrets.DATASET }},BUCKET_NAME=${{ secrets.BUCKET_NAME }},DESTINO_BLOB=${{ secrets.DESTINO_BLOB }}
