name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: analitica-contact-center-dev
  SERVICE_NAME: cuentasmedicas-siifa
  REGION: us-central1
  REPOSITORY: proyecto-dataton-artifacts
  IMAGE: cuentasmedicas-siifa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Autenticarse en GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build imagen
        run: |
          gcloud builds submit \
            --tag $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }}
            --async
      - name: Deploy a Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --memory=2Gi \
            --cpu=1 \
            --timeout=900 \
            --concurrency=1
